stages:
  complete-basic_report:
    cmd: dz run-step basic_report complete
    deps:
    - src/basic_report.py
    - src/collect.py
    params:
    - zimmer.yaml:
      - aswan_projects.bbc-local.current_leaf
      - envs.complete.params.last_days
    outs:
    - data/bbc-sentiment/basic_report/complete/article.parquet:
        persist: true
    - data/bbc-sentiment/basic_report/complete/article_locator.parquet:
        persist: true
    - reports/complete/latest.md:
        cache: false
    - reports/complete/sentiment.jpg:
        cache: false
