stages:
  complete-basic_report:
    cmd: dz run-step basic_report complete
    deps:
    - src/basic_report.py
    - src/collect.py
    params:
    - zimmer.yaml:
      - aswan_projects.bbc-local.current_leaf
      - envs.complete.params.last_days
    outs:
    - reports/complete/sentiment.jpg:
        cache: false
